# Generated by Django 4.2.30 on 2026-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='worker_line_status',
            field=models.CharField(choices=[('Floating', 'Floating'), ('Original', 'Original')], default='Floating', max_length=50),
        ),
    ]
